version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  suikoden_election_2022_frontend_build_and_test:
    docker:
      - image: cimg/node:19.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn

workflows:
  circleci_main_workflow:
    jobs:
      - suikoden_election_2022_frontend_build_and_test
