version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  suikoden_election_2022_frontend_build_and_test:
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      # - run:
      #     name: Run tests
      #     command: yarn test

workflows:
  circleci_main_workflow:
    jobs:
      - suikoden_election_2022_frontend_build_and_test
