version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  suikoden_election_2022_frontend_build_and_test:
    docker:
      # FIXME: リリースされ次第バージョンを上げること
      # https://hub.docker.com/r/cimg/node/tags?page=1&name=18
      - image: cimg/node:18.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      # - run:
      #     name: Run tests
      #     command: yarn test

workflows:
  circleci_main_workflow:
    jobs:
      - suikoden_election_2022_frontend_build_and_test
