name: (GitHub Actions) Cypress

on:
  push:

jobs:
  cypress_gss2022_frontend:
    name: Cypress での E2E テスト
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: ["18.x"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Node.js のセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: 日本語フォントのインストールを行う
        run: |
          sudo apt install -y fonts-migmix
      - name: Cypress 用のパッケージをインストールする
        run: |
          sudo apt install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: npm-run-all をグローバルにインストールする
        run: |
          npm install -g npm-run-all
      - name: アーティファクト用のディレクトリを作成する
        run: |
          mkdir cypress/videos
          mkdir cypress/screenshots
      - name: Npm のパッケージをインストールする ($ yarn install)
        run: |
          yarn install --frozen-lockfile
      - name: Cypress Info を実行する
        run: |
          npx cypress info
      - name: Cypress を実行する
        uses: cypress-io/github-action@v5.8.1
        with:
          build: npx next build
          start: npx next start --port 3100
          wait-on: 'http://localhost:3100'
          wait-on-timeout: 30 # seconds
          working-directory: ./
          config-file: cypress.config.ts
          record: false
          browser: chrome
          # browser: firefox
          # browser: edge
        env:
          DEPLOYMENT_ENVIRONMENT: production
      - name: Cypress のスクリーンショットをアップロードする
        uses: actions/upload-artifact@v3.1.2
        if: always()
        with:
          name: cypress_screenshots
          path: cypress/screenshots/
      - name: Cypress の動画をアップロードする
        uses: actions/upload-artifact@v3.1.2
        if: always()
        with:
          name: cypress_videos
          path: cypress/videos/
