name: (GitHub Actions) Danger
on:
  pull_request:
    branches:
      - '**'
      - '!main'

jobs:
  build:
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Danger
      uses: danger/danger-js@11.0.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DANGER_DISABLE_TRANSPILATION: true
