name: (GitHub Actions) Node.js CI

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - development
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: "false"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    # Enable tmate debugging of manually-triggered workflows if the input option was provided
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' }}
      timeout-minutes: 15
      with:
        sudo: false
        limit-access-to-actor: true
    - name: $ yarn install
      run: |
        yarn install --frozen-lockfile
    - name: ESLint
      run: |
        yarn lint
    # - name: Jest
    #   run: |
    #     yarn test
    # - name: Codecov の結果をアップロードする
    #   uses: codecov/codecov-action@v2
    #   with:
    #     directory: ./.coverage
