name: (GitHub Actions) Node.js CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        # FIXME: 不具合により一時的にキャッシュを無効化する
        # https://github.com/actions/setup-node/issues/516#issuecomment-1153635273
        # cache: yarn
    # Enable tmate debugging of manually-triggered workflows if the input option was provided
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' }}
      timeout-minutes: 15
      with:
        sudo: true
        limit-access-to-actor: true
    - name: $ yarn install
      run: |
        yarn install --frozen-lockfile
    - name: ESLint
      run: |
        yarn lint
    - name: Jest によるテストを実行する
      run: |
        npx jest
    - name: Codecov の結果をアップロードする
      run: |
        echo 'TODO: Codecov の結果をアップロードする'
      # uses: codecov/codecov-action@v2
      # with:
      #   directory: ./.coverage
